# docker compose -f ./server/DevOps/docker/docker-compose-keycloak.yml up
version: '3.1'

services:
  keycloak:
    image: jboss/keycloak
    volumes:
      - ./docker-volume:/opt/jboss/keycloak/data
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Adm1NJourn3y20!
