# docker compose -f ./server/DevOps/docker/docker-compose.yml up
version: '3.1'

# BUILDS SUCCESSFULLY
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3001:3001'

  # BUILDS SUCCESSFULLY
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    restart: always
    depends_on:
      - server

  keycloak:
    image: jboss/keycloak
    volumes:
      - ./docker-volume:/opt/jboss/keycloak/imports
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=Adm1NJourn3y20!
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
    depends_on:
      - server
      - client
    command: ['/bin/sh', '/importUsers.sh']
