# docker compose -f ./server/DevOps/docker/docker-compose-tests.yml up
version: '3.1'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - server

  tests:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      - client
    command: yarn run cy:run

  keycloak:
    image: jboss/keycloak
    ports:
      - '8080:8080'
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_IMPORT=
    # import configuration file
    # docker run -e KEYCLOAK_USER=<USERNAME> -e KEYCLOAK_PASSWORD=<PASSWORD> \
    # -e KEYCLOAK_IMPORT=/tmp/example-realm.json -v /tmp/example-realm.json:/tmp/example-realm.json
