name: tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-app:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build Server
        run:
          working-directory: ./server

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Install Dependancies
        run: yarn install --frozen-lockfile

      - name: Build Server
        run: yarn run build

      - name: Run Server
        run: yarn run serve

      - name: Build Client
        run:
          working-directory: ./client

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Remove node_modules
        run: rm -rf node_modules

      - name: Install Dependancies
        run: yarn install --frozen-lockfile

      - name: Build Client
        run: yarn run build

      - name: Run Client
        run: yarn run serve

      - name: Run Client Tests
        run: yarn run cy:run
