name: tests

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build-server:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./server
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup server node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache server node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Remove server node_modules
        run: rm -rf node_modules

      - name: Install server dependancies
        run: yarn install --frozen-lockfile

      - name: Build Server
        run: yarn run build

      - name: Run Server
        run: yarn run serve

  build-client:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ./client
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup client node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache client node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Remove client node_modules
        run: rm -rf node_modules

      - name: Install client dependancies
        run: yarn install --frozen-lockfile

      - name: Build Client
        run: yarn run build

      - name: Run Client
        run: yarn run serve

      - name: Run Client Tests
        run: yarn run cy:run
